### ISSUE TITLE
Ember.getOwner supported from Ember 2.4

### ISSUE THREAD

**Issue by hashg** [nolanlawson/ember-pouch#171]
Ember.getOwner is supported from 2.4 onwards and `ember-getowner-polyfill` is not required any more. 

I get his error, while using ember-pouch on Ember-cli 2.11 without installing ember-getowner-polyfill.

```
Error while processing route: index Could not find module `ember-getowner-polyfill` imported from `ember-pouch/adapters/pouch` Error: Could not find module `ember-getowner-polyfill` imported from `ember-pouch/adapters/pouch`
    at missingModule (http://localhost:4200/assets/vendor.js:248:11)
    at findModule (http://localhost:4200/assets/vendor.js:259:17)
    at Module.findDeps (http://localhost:4200/assets/vendor.js:199:24)
    at findModule (http://localhost:4200/assets/vendor.js:262:11)
    at Module.findDeps (http://localhost:4200/assets/vendor.js:199:24)
    at findModule (http://localhost:4200/assets/vendor.js:262:11)
    at Module.findDeps (http://localhost:4200/assets/vendor.js:199:24)
    at findModule (http://localhost:4200/assets/vendor.js:262:11)
    at requireModule (http://localhost:4200/assets/vendor.js:29:15)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:114181:20)
logError @ ember.debug.js:28570
```

```
ember.debug.js:17634 Error: Could not find module `ember-getowner-polyfill` imported from `ember-pouch/adapters/pouch`
    at missingModule (loader.js:239)
    at findModule (loader.js:250)
    at Module.findDeps (loader.js:190)
    at findModule (loader.js:253)
    at Module.findDeps (loader.js:190)
    at findModule (loader.js:253)
    at Module.findDeps (loader.js:190)
    at findModule (loader.js:253)
    at requireModule (loader.js:20)
    at Class._extractDefaultExport (resolver.js:385)
```

#### Addition env details
```
Ember-cli: 2.11.0
Ember      : 2.11.0
Ember Data : 2.11.0
jQuery     : 3.1.1
```

**Comment by srsgores** [comment]
Clearly [line 3](https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L3) should be removed.and [line 151](https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L151) changed to `Ember.getOwner`

**Comment by broerse** [comment]
I agree. Can you submit a PR for this?

**Comment by ntodd** [comment]
@broerse I have submitted a pull request for this: #173

**Comment by broerse** [comment]
Thanks! Will commit today and version bump before Monday.
